### ISSUE TITLE
Doesn't works in Wayland with Gnome 41

### ISSUE THREAD

**Issue by arumihsnek** [iberianpig/fusuma-plugin-appmatcher#3]
Hi people,

the contexts in wayland seems to not work with a config.yml file that works in the same gnome sesion but in X.

Also, in Wayland, when i do `fusuma-appmatcher -l` returns `xprop: error: Invalid window id format: WM_CLASS.`

Thanks for this wonderful app.

**Comment by iberianpig** [comment]
Hi @arumihsnek 
Which Linux distribution are you using?

Would you please paste the output of the following commands?

```sh
fusuma --version
```
```sh
fusuma-appmatcher --version
```

```sh
env | grep -e XDG_CURRENT_DESKTOP -e XDG_SESSION_TYPE
```

**Comment by iberianpig** [comment]
I think appmatcher is detecting as x11 on your env.

https://github.com/iberianpig/fusuma-plugin-appmatcher/blob/master/lib/fusuma/plugin/appmatcher.rb#L16-L21

**Comment by arumihsnek** [comment]
Hi!

fusuma --version:

```
jcfitn@archg14 ~> fusuma --version
I, [2021-12-14T09:35:53.793515 #2086]  INFO -- : reload config: /home/jcfitn/.config/fusuma/config.yml
I, [2021-12-14T09:35:53.997708 #2086]  INFO -- : ---------------------------------------------
I, [2021-12-14T09:35:53.998501 #2086]  INFO -- : Fusuma: 2.1.0
I, [2021-12-14T09:35:54.001983 #2086]  INFO -- : libinput: 1.19.3
I, [2021-12-14T09:35:54.002100 #2086]  INFO -- : ruby 3.0.3p157
I, [2021-12-14T09:35:54.003450 #2086]  INFO -- : OS: Linux 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000
I, [2021-12-14T09:35:54.005290 #2086]  INFO -- : Distribution: Arch Linux \r (\l)
I, [2021-12-14T09:35:54.011205 #2086]  INFO -- : Desktop session: gnome wayland
I, [2021-12-14T09:35:54.011317 #2086]  INFO -- : ---------------------------------------------
I, [2021-12-14T09:35:54.011348 #2086]  INFO -- : Enabled Plugins: 
I, [2021-12-14T09:35:54.011561 #2086]  INFO -- :   Fusuma::Plugin::Buffers::AppmatcherBuffer
I, [2021-12-14T09:35:54.011592 #2086]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
[...]
```
fusuma-appmatcher --version

`0.1.4`

env | grep -e XDG_CURRENT_DESKTOP -e XDG_SESSION_TYPE



```
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_TYPE=wayland


```

and my appmatcher.rb
```

# frozen_string_literal: true

require 'fusuma/plugin/appmatcher/version'

require_relative 'appmatcher/x11'
require_relative 'appmatcher/gnome'

module Fusuma
  module Plugin
    # Detect focused applications.
    module Appmatcher
      module_function

      # @return [Class]
      def backend_klass
        if ENV['DESKTOP_SESSION'] == 'ubuntu-wayland'
          Gnome
        else
          X11
        end
      end
    end
  end
end
```

**Comment by arumihsnek** [comment]
Hi!

fusuma --version:

```
I, [2021-12-14T09:57:20.645592 #6376]  INFO -- : reload config: /home/jcfitn/.config/fusuma/config.yml
I, [2021-12-14T09:57:20.849988 #6376]  INFO -- : ---------------------------------------------
I, [2021-12-14T09:57:20.850767 #6376]  INFO -- : Fusuma: 2.1.0
I, [2021-12-14T09:57:20.854407 #6376]  INFO -- : libinput: 1.19.3
I, [2021-12-14T09:57:20.854523 #6376]  INFO -- : ruby 3.0.3p157
I, [2021-12-14T09:57:20.855891 #6376]  INFO -- : OS: Linux 5.15.7-arch1-1 #1 SMP PREEMPT Wed, 08 Dec 2021 14:33:16 +0000
I, [2021-12-14T09:57:20.857459 #6376]  INFO -- : Distribution: Arch Linux \r (\l)
I, [2021-12-14T09:57:20.861636 #6376]  INFO -- : Desktop session: gnome wayland
I, [2021-12-14T09:57:20.861745 #6376]  INFO -- : ---------------------------------------------
I, [2021-12-14T09:57:20.861779 #6376]  INFO -- : Enabled Plugins: 
I, [2021-12-14T09:57:20.862013 #6376]  INFO -- :   Fusuma::Plugin::Buffers::AppmatcherBuffer
I, [2021-12-14T09:57:20.862079 #6376]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2021-12-14T09:57:20.862100 #6376]  INFO -- :   Fusuma::Plugin::Buffers::KeypressBuffer
I, [2021-12-14T09:57:20.862123 #6376]  INFO -- :   Fusuma::Plugin::Buffers::TimerBuffer
I, [2021-12-14T09:57:20.862142 #6376]  INFO -- :   Fusuma::Plugin::Detectors::AppmatcherDetector
I, [2021-12-14T09:57:20.862161 #6376]  INFO -- :   Fusuma::Plugin::Detectors::KeypressDetector
I, [2021-12-14T09:57:20.862183 #6376]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2021-12-14T09:57:20.862201 #6376]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2021-12-14T09:57:20.862221 #6376]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2021-12-14T09:57:20.862239 #6376]  INFO -- :   Fusuma::Plugin::Events::Records::AppmatcherRecord
I, [2021-12-14T09:57:20.862256 #6376]  INFO -- :   Fusuma::Plugin::Events::Records::ContextRecord
I, [2021-12-14T09:57:20.862273 #6376]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2021-12-14T09:57:20.862291 #6376]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2021-12-14T09:57:20.862308 #6376]  INFO -- :   Fusuma::Plugin::Events::Records::KeypressRecord
I, [2021-12-14T09:57:20.862326 #6376]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2021-12-14T09:57:20.862345 #6376]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2021-12-14T09:57:20.862566 #6376]  INFO -- :   Fusuma::Plugin::Executors::SendkeyExecutor
I, [2021-12-14T09:57:20.862580 #6376]  INFO -- :   Fusuma::Plugin::Filters::KeypressFilter
I, [2021-12-14T09:57:20.862592 #6376]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2021-12-14T09:57:20.862606 #6376]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2021-12-14T09:57:20.862619 #6376]  INFO -- :   Fusuma::Plugin::Inputs::AppmatcherInput
I, [2021-12-14T09:57:20.862631 #6376]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2021-12-14T09:57:20.862644 #6376]  INFO -- :   Fusuma::Plugin::Inputs::TimerInput
I, [2021-12-14T09:57:20.862659 #6376]  INFO -- :   Fusuma::Plugin::Parsers::AppmatcherParser
I, [2021-12-14T09:57:20.862672 #6376]  INFO -- :   Fusuma::Plugin::Parsers::KeypressParser
I, [2021-12-14T09:57:20.862686 #6376]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2021-12-14T09:57:20.862702 #6376]  INFO -- : ---------------------------------------------

```
fusuma-appmatcher --version

`0.1.4`

env | grep -e XDG_CURRENT_DESKTOP -e XDG_SESSION_TYPE



```
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_TYPE=wayland


```

and my appmatcher.rb
```

# frozen_string_literal: true

require 'fusuma/plugin/appmatcher/version'

require_relative 'appmatcher/x11'
require_relative 'appmatcher/gnome'

module Fusuma
  module Plugin
    # Detect focused applications.
    module Appmatcher
      module_function

      # @return [Class]
      def backend_klass
        if ENV['DESKTOP_SESSION'] == 'ubuntu-wayland'
          Gnome
        else
          X11
        end
      end
    end
  end
end
```

**Comment by iberianpig** [comment]
> fusuma-appmatcher --version
0.1.4

Please update fusuma-pligin-appmatcher.

`gem update fusuma-pligin-appmatcher`

**Comment by iberianpig** [comment]
I tried Fusuma on Gnome 41 with fedora 35.
But, fusuma-appmatcher -l got the following errors.

```
[iberianpig@fedora ~]$ fusuma-appmatcher -l
/home/iberianpig/.local/share/gem/ruby/gems/fusuma-plugin-appmatcher-0.1.6/lib/fusuma/plugin/appmatcher/gnome.rb:110:in `gnome_shell_eval': unhandled exception
        from /home/iberianpig/.local/share/gem/ruby/gems/fusuma-plugin-appmatcher-0.1.6/lib/fusuma/plugin/appmatcher/gnome.rb:63:in `running_applications'
        from /home/iberianpig/.local/share/gem/ruby/gems/fusuma-plugin-appmatcher-0.1.6/exe/fusuma-appmatcher:23:in `<top (required)>'
        from /home/iberianpig/bin/fusuma-appmatcher:23:in `load'
        from /home/iberianpig/bin/fusuma-appmatcher:23:in `<main>'
```

fusuma-appmatcher send Javascript code with  D-Bus, then eval it in Gnome Shell.
In Gnome 41, sending Javascript and eval seems limited and cannot be executed.
I am looking for a workaround to notify Fusuma when the active window changes.

**Comment by frieser** [comment]
> I tried Fusuma on Gnome 41 with fedora 35. But, fusuma-appmatcher -l got the following errors.
> 
> ```
> [iberianpig@fedora ~]$ fusuma-appmatcher -l
> /home/iberianpig/.local/share/gem/ruby/gems/fusuma-plugin-appmatcher-0.1.6/lib/fusuma/plugin/appmatcher/gnome.rb:110:in `gnome_shell_eval': unhandled exception
>         from /home/iberianpig/.local/share/gem/ruby/gems/fusuma-plugin-appmatcher-0.1.6/lib/fusuma/plugin/appmatcher/gnome.rb:63:in `running_applications'
>         from /home/iberianpig/.local/share/gem/ruby/gems/fusuma-plugin-appmatcher-0.1.6/exe/fusuma-appmatcher:23:in `<top (required)>'
>         from /home/iberianpig/bin/fusuma-appmatcher:23:in `load'
>         from /home/iberianpig/bin/fusuma-appmatcher:23:in `<main>'
> ```
> 
> fusuma-appmatcher send Javascript code with D-Bus, then eval it in Gnome Shell. In Gnome 41, sending Javascript and eval seems limited and cannot be executed. I am looking for a workaround to notify Fusuma when the active window changes.

Same error in Arch Linux, Gnome 41 and Wayland with fusuma-appmatcher 0.1.6

**Comment by iberianpig** [comment]
Thanks for reporting.
I'm going to release the new version of fusuma that bundles gnome-extensions to solve this problem.

**Comment by AIGamer28100** [comment]
Hi tried on Ubuntu 21.10 with Gnome 40.4.0 version and fusuma-plugin-appmatcher (0.3.0)

and I am getting this error when I try to install the gnome-extension
```
~$ sudo fusuma-appmatcher --install-gnome-extension
Traceback (most recent call last):
	4: from /usr/local/bin/fusuma-appmatcher:23:in `<main>'
	3: from /usr/local/bin/fusuma-appmatcher:23:in `load'
	2: from /var/lib/gems/2.7.0/gems/fusuma-plugin-appmatcher-0.3.0/exe/fusuma-appmatcher:33:in `<top (required)>'
	1: from /var/lib/gems/2.7.0/gems/fusuma-plugin-appmatcher-0.3.0/lib/fusuma/plugin/appmatcher/gnome_extensions/installer.rb:15:in `install'
/var/lib/gems/2.7.0/gems/fusuma-plugin-appmatcher-0.3.0/lib/fusuma/plugin/appmatcher/user_switcher.rb:33:in `as_user': missing keyword: :proctitle (ArgumentError)

```

But I am able to get an output for 

```

~$ fusuma-appmatcher -l
Gjs
Slack
Google-chrome
...

```
