### ISSUE TITLE
Unable to install the gnome extension

### ISSUE THREAD

**Issue by AIGamer28100** [iberianpig/fusuma-plugin-appmatcher#5]
Hi tried on Ubuntu 21.10 with Gnome 40.4.0 version and fusuma-plugin-appmatcher (0.3.0)

and I am getting this error when I try to install the gnome-extension
```
~$ sudo fusuma-appmatcher --install-gnome-extension
Traceback (most recent call last):
	4: from /usr/local/bin/fusuma-appmatcher:23:in `<main>'
	3: from /usr/local/bin/fusuma-appmatcher:23:in `load'
	2: from /var/lib/gems/2.7.0/gems/fusuma-plugin-appmatcher-0.3.0/exe/fusuma-appmatcher:33:in `<top (required)>'
	1: from /var/lib/gems/2.7.0/gems/fusuma-plugin-appmatcher-0.3.0/lib/fusuma/plugin/appmatcher/gnome_extensions/installer.rb:15:in `install'
/var/lib/gems/2.7.0/gems/fusuma-plugin-appmatcher-0.3.0/lib/fusuma/plugin/appmatcher/user_switcher.rb:33:in `as_user': missing keyword: :proctitle (ArgumentError)

```

But I am able to get an output for 

```

~$ fusuma-appmatcher -l
Gjs
Slack
Google-chrome
...

**Comment by iberianpig** [comment]
Hi, @AIGamer28100 

Thanks for reporting!
Please update fusuma-plugin-appmatcher.
```bash
gem update fusuma-plugin-appmatcher
```
